version: 2.1

parameters:
  greenflare-release:
    type: string
    default: "0.84"
  python-ver-macos:
    type: string
    default: "3.8.6"
  python-ver-macos-major:
    type: string
    default: "3.8"
orbs:
  python: circleci/python@0.3.0
  win: circleci/windows@2.4.0

jobs:
  ubuntu-build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python --version
            python build_binary.py build_exe
            tar -zcvf linux-build.tar.gz build/
            mkdir results/
            mv linux-build.tar.gz results/
          name: Freeze Linux Binary
      - store_artifacts:
          path: results/

  windows-build:
    executor: win/default
    environment:
      GFLAREVER: << pipeline.parameters.greenflare-release >>
    steps:
      - checkout
      - python/load-cache
      - python/save-cache
      - run:
          name: Install Python
          command: |
            choco install python --version=3.8.6
            refreshenv
            python --version
            $Env:Path
      - run:
          name: Install dependencies
          command: |
            pip install --user pip --upgrade
            pip install --user -r requirements.txt
            pip install cx-freeze==6.1
      - run:
          name: Freeze Windows Programme
          command: |
            python build_binary.py build_exe
            tar.exe -a -c -f greenflare-${GFLAREVER}-x86_64-1.zip build
            mkdir results
            move greenflare-*.zip results/
      - store_artifacts:
          path: results/

  macos-build:
    macos:
      xcode: 12.0.0
    environment:
      GFLAREVER: << pipeline.parameters.greenflare-release >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - python-build-cache-3.8.6
            - python-venv-3.8.6
      - run:
          name: Install Python
          command: |
            cd macos
            chmod +x install-custom-python.sh
            ./install-custom-python.sh
            cd ..
      - run:
          name: Install dependencies
          command: |
            python -m pip install pip --upgrade
            python -m pip install -r requirements.txt
            python -m pip install py2app==0.22
      - save_cache:
          key: python-build-cache-3.8.6
          paths:
            - ~/python-build
      - save_cache:
          key: python-venv-3.8.6
          paths:
            - ~/.venv
      - run:
          name: Freeze macOS app
          command: |
            python setup-py2app.py py2app
            chmod +x macos/launch-mac
            cp macos/launch-mac dist/Greenflare.app/Contents/MacOS/
            plutil -replace CFBundleExecutable -string launch-mac dist/Greenflare.app/Contents/Info.plist
      - run:
          name: Package .dmg app bundle
          command: |
            mkdir results/
            cd dist/
            hdiutil create ./greenflare-${GFLAREVER}-x86_64-1.dmg -srcfolder Greenflare.app -ov
            mv greenflare-*.dmg ../results/
      - store_artifacts:
          path: results/
workflows:
  main:
    jobs:
      # - ubuntu-build
      - windows-build
        filters:
          branches:
             only:
               - master
      - macos-build
        filters:
          branches:
            only:
              - master
