version: 2.1

orbs:
  python: circleci/python@0.3.0
  win: circleci/windows@2.4.0

jobs:
  ubuntu-build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python build_binary.py build_exe && tar -zcvf linux-build.tar.gz build/ && mkdir results/ && mv linux-build.tar.gz results/ 
          name: Build Test
      - store_artifacts:
          path: results/
  windows-build:
    executor: win/default
    steps:
      - checkout
      - python/load-cache
      - python/save-cache
      - run:
          name: install dependencies
          command: |
            pip install --user pip --upgrade
            pip install --user -r requirements.txt
      - run:
          name: run cxfreeze
          command: |
            python build_binary.py build_exe
            tar.exe -a -c -f windows-build.zip build
            mkdir results
            move windows-build.zip results/ 
          
      - store_artifacts:
          path: results/      

workflows:
  main:
    jobs:
      - ubuntu-build
      - windows-build
