version: 2.1

parameters:
  greenflare-release:
    type: string
    default: "0.62"
  python-ver-macos:
    type: string
    default: "3.8.5"
  python-ver-macos-major:
    type: string
    default: "3.8"
orbs:
  python: circleci/python@0.3.0
  win: circleci/windows@2.4.0

jobs:
  ubuntu-build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python --version
            python build_binary.py build_exe
            tar -zcvf linux-build.tar.gz build/
            mkdir results/ 
            mv linux-build.tar.gz results/ 
          name: Build Test
      - store_artifacts:
          path: results/
  
  windows-build:
    executor: win/default
    environment:
      GFLAREVER: << pipeline.parameters.greenflare-release >>
    steps:
      - checkout
      - python/load-cache
      - python/save-cache
      - run:
          name: upgrade python
          command: |
            choco install python --version=3.8.2
            refreshenv
            python --version
            $Env:Path
      - run:
          name: install dependencies
          command: |
            pip install --user pip --upgrade
            pip install --user -r requirements.txt
            pip install cx-freeze==6.1
      - run:
          name: run cxfreeze
          command: |
            python build_binary.py build_exe
            tar.exe -a -c -f greenflare-${GFLAREVER}-x86_64-1.zip build
            mkdir results
            move greenflare-*.zip results/          
      - store_artifacts:
          path: results/
  
  macos-build:
    macos: 
      xcode: 12.0.0
    environment:
      GFLAREVER: << pipeline.parameters.greenflare-release >>
      PYTHONVER: << pipeline.parameters.python-ver-macos >>
      PYTHONVERMAJOR: << pipeline.parameters.python-ver-macos-major >>
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: download python
          command: curl -O https://www.python.org/ftp/python/${PYTHONVER}/python-${PYTHONVER}-macosx10.9.pkg
      - run:
          name: install python
          command: sudo installer -pkg python-${PYTHONVER}-macosx10.9.pkg -target /
      - run: 
          name: install dependencies
          command: |
            python${PYTHONVERMAJOR} -m pip install pip --upgrade
            python${PYTHONVERMAJOR} -m pip install -r requirements.txt
            python${PYTHONVERMAJOR} -m pip install py2app==0.22
      - run:
          name: freeze macos app
          command: python${PYTHONVERMAJOR} setup-py2app.py py2app
      - run:
          name: package .dmg app bundle
          command: |
            mkdir results/
            cd dist/
            hdiutil create ./greenflare-${GFLAREVER}-x86_64-1.dmg -srcfolder greenflare.app -ov
            mv greenflare-*.dmg ../results/            
      - store_artifacts:
          path: results/
workflows:
  main:
    jobs:
      # - ubuntu-build
      # - windows-build
      - macos-build