---
jobs:
  macos-build:
    environment:
      GFLAREVER: "<< pipeline.parameters.greenflare-release >>"
    macos:
      xcode: "12.0.0"
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - python-build-cache-3.8.6
            - python-venv-3.8.6
      -
        run:
          command: |
              cd macos
              chmod +x install-custom-python.sh
              ./install-custom-python.sh
              cd ..
          name: "Install Python"
      -
        run:
          command: |
              python3 -m pip install pip --upgrade
              python3 -m pip install -r requirements.txt
              python3 -m pip install py2app==0.22
          name: "Install dependencies"
      -
        save_cache:
          key: python-build-cache-3.8.6
          paths:
            - ~/python-build
      -
        save_cache:
          key: python-venv-3.8.6
          paths:
            - ~/.venv
      -
        run:
          command: |
              python3 setup-py2app.py py2app
              chmod +x macos/launch-mac
              cp macos/launch-mac dist/Greenflare.app/Contents/MacOS/
              plutil -replace CFBundleExecutable -string launch-mac dist/Greenflare.app/Contents/Info.plist
          name: "Freeze macOS app"
      -
        run:
          command: |
              mkdir results/
              cd dist/
              hdiutil create ./greenflare-${GFLAREVER}-x86_64-1.dmg -srcfolder Greenflare.app -ov
              mv greenflare-*.dmg ../results/
          name: "Package .dmg app bundle"
      -
        store_artifacts:
          path: results/
  ubuntu-build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      -
        run:
          command: |
              python --version
              python build_binary.py build_exe
              tar -zcvf linux-build.tar.gz build/
              mkdir results/
              mv linux-build.tar.gz results/
          name: "Freeze Linux Binary"
      -
        store_artifacts:
          path: results/
  windows-build:
    environment:
      GFLAREVER: "<< pipeline.parameters.greenflare-release >>"
    executor: win/default
    steps:
      - checkout
      - python/load-cache
      - python/save-cache
      -
        run:
          command: |
              choco install python --version=3.8.6
              refreshenv
              python --version
              $Env:Path
          name: "Install Python"
      -
        run:
          command: |
              pip install --user pip --upgrade
              pip install --user -r requirements.txt
              pip install cx-freeze==6.1
          name: "Install dependencies"
      -
        run:
          command: |
              python build_binary.py build_exe
              tar.exe -a -c -f greenflare-${GFLAREVER}-x86_64-1.zip build
              mkdir results
              move greenflare-*.zip results/
          name: "Freeze Windows Programme"
      -
        store_artifacts:
          path: results/
orbs:
  python: circleci/python@0.3.0
  win: circleci/windows@2.4.0
parameters:
  greenflare-release:
    default: "0.84"
    type: string
  python-ver-macos:
    default: "3.8.6"
    type: string
  python-ver-macos-major:
    default: "3.8"
    type: string
version: 2.1
workflows:
  main:
    jobs:
      - windows-build:
          filters:
            branches:
              only: master
      - macos-build:
          filters:
            branches:
              only: master
