version: 2.1

parameters:
  greenflare-release:
    type: string
    default: "0.76"
  python-ver-macos:
    type: string
    default: "3.8.5"
  python-ver-macos-major:
    type: string
    default: "3.8"
orbs:
  python: circleci/python@0.3.0
  win: circleci/windows@2.4.0

jobs:
  ubuntu-build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python --version
            python build_binary.py build_exe
            tar -zcvf linux-build.tar.gz build/
            mkdir results/ 
            mv linux-build.tar.gz results/ 
          name: Freeze Linux Binary
      - store_artifacts:
          path: results/
  
  windows-build:
    executor: win/default
    environment:
      GFLAREVER: << pipeline.parameters.greenflare-release >>
    steps:
      - checkout
      - python/load-cache
      - python/save-cache
      - run:
          name: Install Python
          command: |
            choco install python --version=3.8.2
            refreshenv
            python --version
            $Env:Path
      - run:
          name: Install dependencies
          command: |
            pip install --user pip --upgrade
            pip install --user -r requirements.txt
            pip install cx-freeze==6.1
      - run:
          name: Freeze Windows Programme
          command: |
            python build_binary.py build_exe
            tar.exe -a -c -f greenflare-${GFLAREVER}-x86_64-1.zip build
            mkdir results
            move greenflare-*.zip results/          
      - store_artifacts:
          path: results/
  
  macos-build:
    macos: 
      xcode: 12.0.0
    environment:
      GFLAREVER: << pipeline.parameters.greenflare-release >>
      PYTHONVER: << pipeline.parameters.python-ver-macos >>
      PYTHONVERMAJOR: << pipeline.parameters.python-ver-macos-major >>
    steps:
      - checkout
      # - run:
      #     name: Download python
      #     command: curl -O https://www.python.org/ftp/python/${PYTHONVER}/python-${PYTHONVER}-macosx10.9.pkg
      - run:
          name: Install python
          # command: sudo installer -pkg python-${PYTHONVER}-macosx10.9.pkg -target /
          command: |
            cd macos/
            unzip PythonFramework-3.8.pkg.zip
            sudo pax -z -p e -r -f PythonFramework-3.8.pkg/Contents/Archive.pax.gz
            sudo mkdir -p /Library/Frameworks/Python.framework/
            sudo cp -r Versions /Library/Frameworks/Python.framework/
            unzip PythonInstallPip-3.8.pkg.zip
            sudo ./PythonInstallPip-3.8.pkg/Contents/Resources/postflight
            cd ..
      # - restore_cache:
      #     keys:
      #       - pip-cache-{{ checksum "requirements.txt" }}
      - run: 
          name: Install dependencies
          command: |
            /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -m pip install pip --upgrade
            /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -m pip install -r requirements.txt
            /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -m pip install py2app==0.22
      # - save_cache:
      #     key: pip-cache-{{ checksum "requirements.txt" }}
      #     paths:
      #       - /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
      - run:
          name: Freeze macOS app
          command: |
            /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 setup-py2app.py py2app
            chmod +x launch-mac
            cp launch-mac dist/Greenflare.app/Contents/MacOS/
            plutil -replace CFBundleExecutable -string launch-mac dist/Greenflare.app/Contents/Info.plist
      - run:
          name: Package .dmg app bundle
          command: |
            mkdir results/
            cd dist/
            hdiutil create ./greenflare-${GFLAREVER}-x86_64-2.dmg -srcfolder Greenflare.app -ov
            mv greenflare-*.dmg ../results/            
      - store_artifacts:
          path: results/
workflows:
  main:
    jobs:
      # - ubuntu-build
      # - windows-build
      # - macos-build