version: 2.1

orbs:
  python: circleci/python@0.3.0
  win: circleci/windows@2.4.0

jobs:
  ubuntu-build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python build_binary.py build_exe
            tar -zcvf linux-build.tar.gz build/
            mkdir results/ 
            mv linux-build.tar.gz results/ 
          name: Build Test
      - store_artifacts:
          path: results/
  windows-build:
    executor: win/default
    steps:
      - checkout
      - python/load-cache
      - python/save-cache
      - run:
          name: upgrade python
          command: |
            choco install python --version=3.8.2
            refreshenv
            python --version
            $Env:Path
      - run:
          name: install dependencies
          command: |
            pip install --user pip --upgrade
            pip install --user -r requirements.txt
      - run:
          name: run cxfreeze
          command: |
            python build_binary.py build_exe
            tar.exe -a -c -f windows-build.zip build
            mkdir results
            move windows-build.zip results/ 
          
      - store_artifacts:
          path: results/
  
  macos-build:
    macos: 
      xcode: 9.4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - tkinter
      - run:
          name: install tkinter
          command: |
            if [ ! -d "/usr/local/Cellar/tcl-tk/" ]; then
              brew uninstall python@2
              brew uninstall python
              brew update
              brew install tcl-tk
              brew list
            else
              echo "Already cached"
            fi
      - save_cache:
          key: tkinter
          paths:
            - "/usr/local/Cellar/tcl-tk/"
            - "/usr/local/Cellar/openssl@1.1"
      - run:
          name: install pyenv
          command: brew install pyenv
      - run:
          name: compile python 3.8.2 with tkinter
          command: PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6'" MACOSX_DEPLOYMENT_TARGET=10.9 pyenv install 3.8.2
      - run:
          name: set pyenv installation to global
          command: |
            pyenv global 3.8.2
            python --version
      - run: 
          name: install dependencies
          command: |
            python -m pip install pip --upgrade
            python -m pip install -r requirements.txt
      - run:
          name: run cxfreeze
          command: |
            python build_binary.py bdist_mac
            tar -zcvf macos-build.tar.gz build/
            mkdir results/ 
            mv macos-build.tar.gz results/
    
      - store_artifacts:
          path: results/

workflows:
  main:
    jobs:
      # - ubuntu-build
      # - windows-build
      - macos-build